# This file was generated by GoReleaser. DO NOT EDIT.
cask "dollarlint" do
  version "0.1.18"

  on_macos do
    on_intel do
      sha256 "0d5c331ec44af9112d50b3b7b55ef64178c2594b0cfe8e2fe0e4e494b91b57db"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
    on_arm do
      sha256 "7fff5b78df8d3b786509ef850aa6a1f9eb1164ddb8428a33ec4c2694f8bb4e04"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7a1828c333e9a1c7c7f491a15da22e5ac81fd55efe3f09d77a25be1423f55cb"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_linux_amd64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
    on_arm do
      sha256 "dc7bce1a49e7036d07c35753af8a513d6228c21b14f85189d58113f398140263"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_linux_arm64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
  end

  name "dollarlint"
  desc "Validate JSON-family, YAML, and TOML files against their declared JSON Schemas"
  homepage "https://dollarlint.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dollarlint"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dollarlint"] if OS.mac?
  end

  # No zap stanza required

end
