# This file was generated by GoReleaser. DO NOT EDIT.
cask "dollarlint" do
  version "0.1.13"

  on_macos do
    on_intel do
      sha256 "1895c0fa74cae9cacaf7f273776d64d2e2601d81a62ddc2ecae89462f74dee24"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
    on_arm do
      sha256 "12f9f93906c7a416f46f5ae33ab83b9c8471066e74d0bbc2770c3b268cbb0080"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a21382651066ac7ab4ff84dcf2e5fcc272ebb089a47f0b8e9ac161b85fb5e98d"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_linux_amd64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
    on_arm do
      sha256 "45263aeb38b75aff08eca9a9e027b36ed5f5b4d592a13e187cc23fc5103f6ae3"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_linux_arm64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
  end

  name "dollarlint"
  desc "Validate JSON-family, YAML, and TOML files against their declared JSON Schemas"
  homepage "https://dollarlint.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dollarlint"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dollarlint"] if OS.mac?
  end

  # No zap stanza required

end
