# This file was generated by GoReleaser. DO NOT EDIT.
cask "dollarlint" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "a710509ad2feeee658bcab2bd26c34ae69353422ad271f094fede38ca079de76"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
    on_arm do
      sha256 "1aa5b94128c58f49ca1d78e6ac424dbb34a6fdba15ad40cef443291ce04489f4"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
  end

  on_linux do
    on_intel do
      sha256 "9801d3ed8586179b3c0858ac9b5689cd250d2d2c673a0b45ea4bd6f16cb74267"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_linux_amd64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
    on_arm do
      sha256 "3b8df59e0da085a040f453ca01c171130e57834c835cbd937ec5d39de10cc292"
      url "https://github.com/dollarlint/dollarlint/releases/download/v#{version}/dollarlint_#{version}_linux_arm64.tar.gz",
        verified: "github.com/dollarlint/dollarlint/"
    end
  end

  name "dollarlint"
  desc "Validate JSON-family, YAML, and TOML files against their declared JSON Schemas"
  homepage "https://dollarlint.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dollarlint"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dollarlint"] if OS.mac?
  end

  # No zap stanza required

end
