# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dollarlint < Formula
  desc "Validate JSON-family, YAML, and TOML files against their declared JSON Schemas."
  homepage "https://github.com/dollarlint/dollarlint"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.3/dollarlint_0.1.3_darwin_amd64.tar.gz"
      sha256 "1d3f6c964db1cf20944e365f65f7b1621f1c5c74bcfd8c134c3f6a5b7fef626b"

      define_method(:install) do
        bin.install "dollarlint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.3/dollarlint_0.1.3_darwin_arm64.tar.gz"
      sha256 "f4ba18f55dc0df5298e9ac646f5308c23a0f34a9d8c7f34b38041c632716f99b"

      define_method(:install) do
        bin.install "dollarlint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.3/dollarlint_0.1.3_linux_amd64.tar.gz"
      sha256 "efdf8069fd292a8f65ca70df0da705909aa6457e40d22e3bd8b1dde7ce5e2045"
      define_method(:install) do
        bin.install "dollarlint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.3/dollarlint_0.1.3_linux_arm64.tar.gz"
      sha256 "a4ccf3201adc78a6c86518d26f7b3a8fa43b1ced8f18ee5dad84f11e15e128b8"
      define_method(:install) do
        bin.install "dollarlint"
      end
    end
  end

  test do
    system "#{bin}/dollarlint", "--version"
  end
end
