# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dollarlint < Formula
  desc "Validate JSON-family, YAML, and TOML files against their declared JSON Schemas."
  homepage "https://github.com/dollarlint/dollarlint"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.4/dollarlint_0.1.4_darwin_amd64.tar.gz"
      sha256 "e4f199c853905fe3aaad9873f5df20f524e3371759905159d5676e4808c63892"

      define_method(:install) do
        bin.install "dollarlint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.4/dollarlint_0.1.4_darwin_arm64.tar.gz"
      sha256 "371c7ecb902453a428f603b02747bd17a7da70aca8edeb857929085e252f3193"

      define_method(:install) do
        bin.install "dollarlint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.4/dollarlint_0.1.4_linux_amd64.tar.gz"
      sha256 "8f00c1bc65329ce4512995e9dd34f189146265026d181d8daeb6e428673a3095"
      define_method(:install) do
        bin.install "dollarlint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dollarlint/dollarlint/releases/download/v0.1.4/dollarlint_0.1.4_linux_arm64.tar.gz"
      sha256 "e1d6ae941ea4d95ec66bb5deacd8c05cdb151d4380d8ab6988b7a421a344b529"
      define_method(:install) do
        bin.install "dollarlint"
      end
    end
  end

  test do
    system "#{bin}/dollarlint", "--version"
  end
end
